name: run pytests
run-name: ${{ github.actor }} is running pytests
on: [push]
jobs:
  run-pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: python -V
      # - run: pip install -r requirements.txt
      # - run: pip install pytest
      # - run: pytest
      - run: pip install virtualenv
      - run: ./run_tests.sh